stages:
  - build
  - test
  - release
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

build:
  stage: build
  image: docker:stable-dind
  script:
    - echo "Logging to GitLab Container Registry with CI credentials..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build --tag $IMAGE_TAG .
    - docker push $IMAGE_TAG

semantic-release:
  stage: release
  image: enix/semantic-release:gitlab
  only:
    - master
  except:
    - tags
  script:
    - semantic-release --ci

deploy-production:
  stage: deploy
  environment:
    name: production
    url: https://meetup-k8s-outside-networking.slides.enix.io
  only:
    refs:
      - /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$/
  image: dtzar/helm-kubectl:2.13.1
  before_script:
    - apk add --no-cache jq
    - kubectl version
    - helm version
  script:
    - export DOCKER_REGISTRY_SECRET=$(kubectl create secret -n slides-enix-io docker-registry dummy --docker-server=$CI_REGISTRY --docker-username="${CI_DEPLOY_USER}" --docker-password="${CI_DEPLOY_PASSWORD}" -o json --dry-run | jq '.data.".dockerconfigjson"')
    - "sed -i \"s/version: 0.0.1/version: $CI_COMMIT_TAG/\" chart/Chart.yaml"
    - "sed -i \"s/appVersion: 0.0.1/appVersion: $CI_COMMIT_TAG/\" chart/Chart.yaml"
    - helm upgrade --install --wait --set image=$IMAGE_TAG $CI_PROJECT_NAME --set ingressBaseDomain=$KUBE_INGRESS_BASE_DOMAIN --set imagePullSecret="$DOCKER_REGISTRY_SECRET" chart/
